### ISSUE TITLE
Nothing happens?

### ISSUE THREAD

**Issue by Aida-Enna** [xPumaa/DutyAnnouncer#2]
Nothing seems to happen when the duty (roulette or dungeon or undersized) pops. I assume it's supposed to output it to the chatlog, but I get nothing.

**Comment by Cyenia** [comment]
It is only outputed on chat when entering a duty roulette, not when it pops up

**Comment by Aida-Enna** [comment]
Ahhhhh, I see. Sorry for the confusion then, and thanks for your hard work!
